# Generated by Django 6.0.1 on 2026-02-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code for invite links (auto-generated)', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('location', 'Ubicación'), ('system', 'Sistema')], default='text', max_length=20),
        ),
    ]
