# Generated by Django 6.0.1 on 2026-02-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group_invite_code_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='api.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_matches', to='api.user')),
            ],
            options={
                'db_table': 'match_mutes',
                'indexes': [models.Index(fields=['user', 'match'], name='match_mutes_user_id_773254_idx')],
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('match', 'Match'), ('message', 'Message')], max_length=20)),
                ('target_id', models.PositiveIntegerField(help_text='ID of the reported user/group/match/message')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('fake', 'Fake Profile'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='api.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='api.user')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter', 'created_at'], name='reports_reporte_07de2b_idx'), models.Index(fields=['status', 'created_at'], name='reports_status_19e159_idx'), models.Index(fields=['report_type', 'target_id'], name='reports_report__f24d48_idx')],
            },
        ),
    ]
