# Generated by Django 6.0.1 on 2026-02-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_audio_url_message_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Group image URL', max_length=500),
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.group')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='api.user')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='api.user')),
            ],
            options={
                'db_table': 'group_invitations',
                'indexes': [models.Index(fields=['invitee', 'status'], name='group_invit_invitee_7d9a23_idx'), models.Index(fields=['group', 'status'], name='group_invit_group_i_66b8d5_idx')],
            },
        ),
    ]
