# Generated by Django 6.0.1 on 2026-02-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_group_image_url_groupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Group image URL', max_length=500, null=True),
        ),
    ]
