# Generated by Django 6.0.1 on 2026-02-16 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_group_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blitz',
            name='max_opponent_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blitz',
            name='min_opponent_size',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='SoloMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('matched', 'Match mutuo'), ('coordinating', 'Coordinando'), ('ready', 'Listos'), ('started', 'Iniciado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blitz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_matches', to='api.blitz')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_matches_initiated', to='api.user')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_matches_received', to='api.user')),
            ],
            options={
                'db_table': 'solo_matches',
            },
        ),
        migrations.CreateModel(
            name='SoloCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a_categories', models.JSONField(default=list)),
                ('user_a_time', models.JSONField(default=dict)),
                ('user_a_zone', models.JSONField(default=dict)),
                ('user_a_ready', models.BooleanField(default=False)),
                ('user_b_categories', models.JSONField(default=list)),
                ('user_b_time', models.JSONField(default=dict)),
                ('user_b_zone', models.JSONField(default=dict)),
                ('user_b_ready', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Esperando'), ('both_ready', 'Ambos listos'), ('started', 'Iniciado'), ('expired', 'Expirado')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('solo_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordination', to='api.solomatch')),
            ],
            options={
                'db_table': 'solo_coordinations',
            },
        ),
        migrations.AddIndex(
            model_name='solomatch',
            index=models.Index(fields=['user_a', 'status'], name='solo_matche_user_a__8a9a88_idx'),
        ),
        migrations.AddIndex(
            model_name='solomatch',
            index=models.Index(fields=['user_b', 'status'], name='solo_matche_user_b__f764ce_idx'),
        ),
        migrations.AddIndex(
            model_name='solomatch',
            index=models.Index(fields=['status', 'expires_at'], name='solo_matche_status_f7c602_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solomatch',
            unique_together={('user_a', 'user_b')},
        ),
    ]
