# Generated by Django 6.0.1 on 2026-02-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blitz_max_opponent_size_blitz_min_opponent_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blitz',
            name='swipe_mode',
            field=models.CharField(choices=[('leader', 'Solo líder'), ('democratic', 'Democrático')], default='leader', max_length=20),
        ),
    ]
