# Generated by Django 6.0.1 on 2026-02-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blitz_swipe_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='solomatch',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_matches', to='api.chat'),
        ),
        migrations.AddField(
            model_name='solomatch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_matches', to='api.group'),
        ),
    ]
