# Generated by Django 6.0.1 on 2026-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_solomatch_chat_solomatch_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='solomatch',
            name='group_confirmed_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solomatch',
            name='group_confirmed_b',
            field=models.BooleanField(default=False),
        ),
    ]
