# Generated by Django 6.0.1 on 2026-02-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_solo_match_group_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('blitz_match', 'Nuevo Match'), ('blitz_like', 'Grupo te dio Like'), ('blitz_vote_request', 'Votación Pendiente'), ('new_message', 'Nuevo Mensaje'), ('friend_request', 'Solicitud de Amistad'), ('group_invite', 'Invitación a Grupo'), ('meetup_proposed', 'Plan Propuesto'), ('meetup_confirmed', 'Meetup Confirmado'), ('blitz_expiring', 'Blitz por Expirar'), ('solo_connection', 'Conexión Solo Mode'), ('solo_match', 'Match Solo Mode'), ('memory_added', 'Recuerdo Agregado'), ('system', 'Sistema')], max_length=30),
        ),
    ]
