# =============================================================================
#  Nginx — Configuración TEMPORAL (solo HTTP)
#
#  Se usa UNICAMENTE la primera vez para que Certbot pueda verificar
#  el dominio y obtener el certificado SSL.
#
#  Después de obtener el certificado, se reemplaza por default.conf
# =============================================================================

server {
    listen 80;
    server_name jesuslab135.com www.jesuslab135.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'Servidor en configuracion inicial...';
        add_header Content-Type text/plain;
    }
}
