"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Firebase service account credentials path
FIREBASE_SERVICE_ACCOUNT_PATH = Path(os.getenv(
    'FIREBASE_SERVICE_ACCOUNT_PATH',
    str(BASE_DIR / "squapup-3ab7a-firebase-adminsdk-fbsvc-53c50f45a0.json"),
))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

load_dotenv()
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_NAME = os.getenv('DB_NAME')
HOST = os.getenv('HOST')
PORT = os.getenv('PORT')
SECRET_KEY = os.getenv('SECRET_KEY')

# Stripe configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')


# =============================================================================
# TOGGLE — DEBUG
# =============================================================================

# --- ACTIVO: LOCAL ---
#DEBUG = True

# --- INACTIVO: PRODUCCION ---
DEBUG = False


# =============================================================================
# TOGGLE — ALLOWED_HOSTS
# =============================================================================

# --- ACTIVO: LOCAL (acepta cualquier host) ---
#ALLOWED_HOSTS = ['*']

# --- INACTIVO: PRODUCCION (solo tu dominio y la IP del VPS) ---

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv(
        'ALLOWED_HOSTS',
        'jesuslab135.com,www.jesuslab135.com,198.71.54.171,localhost,127.0.0.1,backend,10.0.2.2',
    ).split(',') if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://jesuslab135.com,https://www.jesuslab135.com,https://198.71.54.171',
    ).split(',') if o.strip()
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for ASGI support

    # 'django.contrib.admin',  # Disabled - using Swagger instead
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.staticfiles',  # Disabled - API only, no static files needed

    'api',
    'channels',  # Django Channels for WebSocket

    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'django_prometheus',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.Authentication.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

    # =========================================================================
    # THROTTLING / RATE LIMITING
    # =========================================================================
    # AnonRateThrottle  — limita por IP (usuarios sin token Firebase)
    # UserRateThrottle  — limita por user.pk (usuarios autenticados)
    # ScopedRateThrottle — limita endpoints sensibles (pagos, suscripciones)
    # =========================================================================
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/hour',             # No autenticados: 30 req/hora
        'user': '1000/hour',           # Autenticados: 1000 req/hora
        'fuerza_bruta': '10/min',      # Endpoints financieros: 10 req/min
    },
}

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.logging_middleware.RequestLogMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]


# =============================================================================
# TOGGLE — CORS
# =============================================================================

# --- ACTIVO: LOCAL (acepta cualquier origen) ---
# CORS_ALLOW_ALL_ORIGINS = True

# --- INACTIVO: PRODUCCION (solo origenes especificos) ---
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'https://jesuslab135.com',
    'https://www.jesuslab135.com',
    'http://jesuslab135.com:8080',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://localhost:8000',
    'http://localhost:8001',
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Django Channels - Channel Layer Configuration
# Usa Redis para soporte de WebSocket en producción y desarrollo con Docker
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')  # 'redis' es el nombre del servicio en docker-compose

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, 6379)],
        },
    }
}

# Para desarrollo local sin Docker, usa InMemoryChannelLayer:
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     }
# }


# =============================================================================
# TOGGLE — CACHE (requerido para DRF Throttling)
# =============================================================================

# --- ACTIVO: LOCAL (cache en memoria, se pierde al reiniciar) ---
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'drf-throttle-cache',
#     }
# }

# --- INACTIVO: PRODUCCION (Redis — mismo host que Channel Layers, DB /1) ---
CACHES = {
    'default': {
        'BACKEND': 'django_prometheus.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:6379/1',
    }
}


# =============================================================================
# TOGGLE — BASE DE DATOS
#
# Los valores vienen del archivo .env, asi que el cambio se hace ALLA:
#   LOCAL  (.env):  HOST=localhost   (si corres Django fuera de Docker)
#                   HOST=db          (si corres Django dentro de Docker)
#   PROD   (.env):  HOST=db          (siempre dentro de Docker)
#
# No necesitas cambiar nada aqui. Solo ajusta tu .env.
# =============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': HOST,
        'PORT': PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# LOGGER
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_django': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_request': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'request.log'),
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file_request'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': True,
        }
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CONFIGURACIÓN CORRECTA PARA SPECTACULAR
SPECTACULAR_SETTINGS = {
    'TITLE': 'SquadUp Backend API',
    'DESCRIPTION': 'API for Web and Mobile',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],

    #  SCHEMA PATH PREFIX
    'SCHEMA_PATH_PREFIX': '/api/',

    # =========================================
    # SERVERS — Swagger apunta a ambos entornos
    # =========================================
    'SERVERS': [
        {
            'url': 'https://jesuslab135.com',
            'description': 'Production',
        },
        {
            'url': 'http://jesuslab135.com:8080',
            'description': 'Staging',
        },
        {
            'url': 'http://localhost:8000',
            'description': 'Local Development',
        },
    ],

    #  SECURITY SCHEMES (Directo, sin EXTENSIONS)
    'COMPONENTS': {
        'securitySchemes': {
            'FirebaseAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Firebase ID Token. Format: Bearer {token}',
            }
        }
    },

    #  GLOBAL SECURITY
    'SECURITY': [
        {'FirebaseAuth': []}
    ],
}
